-- resume-public seed: public résumé tables copied verbatim from resume-backlog.
-- Generated once at split time. resume-backlog is never written to.

CREATE TABLE IF NOT EXISTS companies (key TEXT PRIMARY KEY, display TEXT, location TEXT, sort_order INTEGER);
CREATE TABLE IF NOT EXISTS roles (id INTEGER PRIMARY KEY, company_key TEXT, title TEXT, start TEXT, end TEXT, note TEXT, sort_order INTEGER);
CREATE TABLE IF NOT EXISTS accomplishments (id INTEGER PRIMARY KEY AUTOINCREMENT, role_id INTEGER, bullet TEXT, tags TEXT, metric TEXT, date_added TEXT, notes TEXT);
CREATE TABLE IF NOT EXISTS targets (name TEXT PRIMARY KEY, headline TEXT, summary TEXT, include_tags TEXT, boost_tags TEXT, exclude_tags TEXT, max_bullets_per_role INTEGER, num_highlights INTEGER);
CREATE TABLE IF NOT EXISTS profile (section TEXT, key TEXT, value TEXT);

-- profile: 14 rows
INSERT INTO profile ("section","key","value") VALUES ('contact','email','j.r.schumacher@gmail.com');
INSERT INTO profile ("section","key","value") VALUES ('contact','github','github.com/jrschumacher');
INSERT INTO profile ("section","key","value") VALUES ('contact','linkedin','linkedin.com/in/jrschumacher');
INSERT INTO profile ("section","key","value") VALUES ('skill','Languages','Go, TypeScript, Node, React, Svelte, Python, Java');
INSERT INTO profile ("section","key","value") VALUES ('skill','Protocols','gRPC, ConnectRPC, Protobuf, REST, WebSocket, GraphQL, MCP');
INSERT INTO profile ("section","key","value") VALUES ('skill','Databases','Postgres, Redis, MongoDB, DuckDB');
INSERT INTO profile ("section","key","value") VALUES ('skill','Infrastructure','Docker, Terraform, Helm, Kubernetes, Istio, Envoy, GitOps');
INSERT INTO profile ("section","key","value") VALUES ('skill','Other','MQ, Pub/Sub, OpenAPI, AsyncAPI, microfrontends, modular monoliths');
INSERT INTO profile ("section","key","value") VALUES ('community','1','Supported open-source adoption of OpenTDF (github.com/opentdf) through direct community engagement.');
INSERT INTO profile ("section","key","value") VALUES ('community','2','Created and taught a high-school course, "Computer Science Without Computers," introducing core CS concepts.');
INSERT INTO profile ("section","key","value") VALUES ('community','3','Participated in developer meetups and forums to share expertise in Go, system design, and data privacy.');
INSERT INTO profile ("section","key","value") VALUES ('education','Auburn University','B.S. Computer Science · 2003 – 2007');
INSERT INTO profile ("section","key","value") VALUES ('contact','name','Ryan Schumacher');
INSERT INTO profile ("section","key","value") VALUES ('skill','Security & Identity','OIDC, OAuth2, DPoP, token exchange, ABAC/RBAC, HSM, AWS KMS, GCP KMS, Keycloak, Okta, PingFederate, LDAP/Active Directory, OpenTDF/TDF, Cedar');

-- companies: 3 rows
INSERT INTO companies ("key","display","location","sort_order") VALUES ('virtru','Virtru','Remote',0);
INSERT INTO companies ("key","display","location","sort_order") VALUES ('bbva','BBVA USA','',1);
INSERT INTO companies ("key","display","location","sort_order") VALUES ('ventures','38pages / tep.io / Outfit Outdoors / Hatch Safety','',2);

-- roles: 7 rows
INSERT INTO roles ("id","company_key","title","start","end","note","sort_order") VALUES (1,'virtru','Director of Platform','2025-01','present','official title: Staff Architect 2',1);
INSERT INTO roles ("id","company_key","title","start","end","note","sort_order") VALUES (2,'virtru','Staff Architect 2','2024-01','2025-01','title effective Jul 2024',2);
INSERT INTO roles ("id","company_key","title","start","end","note","sort_order") VALUES (3,'virtru','Engineering Manager','2021-01','2024-01',NULL,3);
INSERT INTO roles ("id","company_key","title","start","end","note","sort_order") VALUES (4,'virtru','Staff Engineer','2020-09','2021-01',NULL,4);
INSERT INTO roles ("id","company_key","title","start","end","note","sort_order") VALUES (5,'virtru','Senior Full Stack Engineer','2019-06','2020-09',NULL,5);
INSERT INTO roles ("id","company_key","title","start","end","note","sort_order") VALUES (6,'bbva','Lead Engineer','2017-03','2019-06',NULL,6);
INSERT INTO roles ("id","company_key","title","start","end","note","sort_order") VALUES (7,'ventures','Co-founder / Engineering Lead','2009-02','2018-06',NULL,7);

-- accomplishments: 57 rows
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (1,1,'Informally recognized as Director of Platform by SVP for leading cross-org initiatives and platform strategy, pending formal title update.','leadership, strategy, platform',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (2,1,'Assumed leadership of the platform engineering organization (12 engineers), improving release reliability, product-development consistency, and engineering understanding.','leadership, people, platform, reliability, scale','12 engineers',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (3,1,'Institutionalized cross-team release planning, cutting cycle times from weeks to days.','leadership, process, reliability','cycle time',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (4,1,'Stepped into a cross-functional leadership vacuum during principal absence, collaborating with Support to restore alignment, build trust, and resolve urgent issues with rapid, transparent communication; earned CEO recognition and delivered high-impact fixes in weeks.','leadership, strategy, reliability','ceo recognition',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (5,1,'Architected and led key platform initiatives, collaborating with Product to resolve engineering bottlenecks and demonstrate clear customer value.','architecture, platform, strategy',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (6,1,'Championed developer experience through direct engagement with the open-source community, identifying friction points, guiding adoption, and delivering improvements based on real user needs.','devex, opensource, community',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (7,1,'Directed architectural strategy during principal engineer leave, ensuring continuity of vision and velocity.','architecture, leadership, strategy',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (8,1,'Promoted and mentored staff engineers into technical leads, scaling the team without additional hiring.','leadership, mentorship, people',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (9,2,'Refactored the OpenTDF platform from polyglot microservices into a Go modular monolith in 3 months, unlocking air-gapped deployments beyond Kubernetes and dramatically improving deployment velocity and customer compatibility.','architecture, go, migration, platform, reliability','3 months',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (10,2,'Pushed an admin CLI over a web interface, enabling a rich user experience in weeks instead of months.','devex, cli, architecture','weeks vs months',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (11,2,'Developed the DSP premium platform on top of OpenTDF, driving internal developer onboarding within 4 months and creating the opportunity for 37% net-new growth in company ARR.','platform, devex, growth, revenue','37 percent arr',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (12,2,'Delivered a proof of concept that unlocked a 15% upsell in renewal ARR.','growth, revenue','15 percent upsell',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (13,3,'Delivered a FedRAMP- and GovRAMP-authorized greenfield project to market in 6 months, with 200% YTD growth.','leadership, greenfield, compliance, growth','6 months',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (14,3,'Championed a self-service custom-branding solution, increasing sales by 650% and unlocking 5% ARR growth.','architecture, growth, revenue, devex','650 percent',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (15,3,'Implemented a TypeScript library monorepo, reducing dependency-vulnerability maintenance by 60%.','typescript, monorepo, devex, reliability','60 percent',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (16,3,'Led and mentored a team of 4 engineers on a product with 600k MAU, protecting 1M units of data per month.','leadership, people, mentorship, scale','600k mau',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (17,3,'Drove a microfrontend architecture, increasing deployments by over 400%.','architecture, frontend, microfrontends, devex','400 percent',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (18,3,'Led the Kubernetes OKR for two quarters, achieving 50% faster releases and 95% faster rollbacks.','kubernetes, reliability, devex','50 percent',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (19,3,'Championed Go as a supported language, established a Go guild, drafted best practices, and drove code reviews.','go, leadership, devex, community',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (20,3,'Established an Architectural Decision Records process to drive consistent, efficient decision-making.','architecture, process, strategy',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (21,3,'Promoted a direct report to engineering manager, improving the team''s scaling factor.','leadership, people, mentorship',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (22,4,'Implemented the binary-spec SDK in TypeScript with a focus on performance and developer experience.','typescript, devex, backend',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (23,4,'Developed a web app to power policy management, contributing to a $250k customer upsell.','frontend, growth, revenue','250k',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (24,4,'Guided the team in proper RESTful API design and implemented an OpenAPI spec.','api, architecture, devex',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (25,5,'Developed a pre-launch solution for web SDK usage, protecting a legacy auth token in 2 weeks.','backend, privacy, reliability','2 weeks',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (26,5,'Engaged the developer community through documentation, blogs, sample apps, and local meetups.','community, devex, opensource',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (27,5,'Acted as solution architect for a prospective customer, leading to the first net-new ARR.','architecture, growth, revenue',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (28,6,'Led a team supporting 5,000+ DAU; migrated a legacy application to microfrontends, increasing team velocity by 75%.','leadership, frontend, microfrontends, migration, scale','75 percent',NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (29,7,'Founded and led engineering for 3 ventures over a 9-year span, spanning B2B SaaS and consumer products.','leadership, greenfield, strategy, founder',NULL,NULL,NULL);
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (30,1,'Led platform readiness for first major customer release (v2.0.5 to v2.0.6), anchoring delivery for a $17M client against a ~$42M ARR base.','platform, leadership, strategy, reliability','$17M client / ~$42M ARR','2025','Transitioned from Staff Architect to Director of Platform. Led the customer-facing side: platform API management surface, CLI, admin tooling. ~40% of company revenue riding on this release.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (31,1,'Personally stood up a PingFederate test instance and delivered platform changes to integrate a $17M client''s IdP when the team was at capacity.','identity, platform, judgment','$17M client unblocked','2025','Team was stretched on other priorities so took the integration on individually as Director. PingFederate is a build-it-yourself IdP: highly flexible, nothing pre-built. Good story for hands-on leadership at director level.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (32,1,'Integrated platform with Okta, navigating IdP-specific OIDC claim behavior (Okta does not embed claims on tokens, unlike Keycloak).','identity, platform, sdk',NULL,'2025','Part of broader lesson: OIDC is a standard but IdPs implement it inconsistently. Keycloak embeds all claims natively; Okta does not and does not recommend it even with premium add-ons; PingFederate is fully DIY.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (33,1,'Established OIDC as the platform''s universal identity layer, replacing a bespoke token so the data security platform can plug into any customer IdP.','identity, architecture, strategy, platform',NULL,'2025','Foundational design philosophy: platform must plug in anywhere, and authorization requires identity. OIDC increasingly appears as a named requirement in job postings, so keep this thread prominent.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (34,1,'Implemented DPoP to prevent token theft and replay attacks on cross-platform token handoffs during policy federation key splits.','identity, security, crypto, architecture',NULL,'2025','Policy federation requires sending tokens to other platforms for key split operations, a highly sensitive handoff. DPoP binds tokens to a key pair.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (35,1,'Designed token exchange flows to complement DPoP, enabling services to act on a user''s behalf downstream without forwarding sender-bound tokens.','identity, security, architecture',NULL,'2025','DPoP-bound tokens cannot be forwarded as-is, so token exchange mints properly scoped and bound tokens for each hop. Pairs with the DPoP row as one coherent story.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (36,1,'Built a unified cache manager adopted across all platform services, replacing scattered per-service caching with one consistent interface.','platform, architecture, reliability',NULL,'2025','Eliminated disparate cache implementations across services. Consistency and performance play.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (37,1,'Architected multi-phase KAS brokering for performance and security hardening, then deliberately deferred implementation when customer need was unproven, avoiding over-engineering.','crypto, architecture, judgment, product-collab',NULL,'2025','Leadership was split on necessity. Worked with Product to apply a two-way-door policy. Customers were fine without it through 2025, validating the deferral. Picked up personally for development in 2026 Q2. Strong judgment story: knowing what NOT to build.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (38,1,'Architected and built a multi-strategy Entity Resolution Service (SQL, LDAP, fallbacks), removing the platform''s hard Keycloak dependency and unblocking forward-deployment engineers on legacy customer environments.','identity, architecture, platform, judgment',NULL,'2025','ERS was tightly coupled to Keycloak, so FDEs put Keycloak in front of every customer IdP: extra moving part plus implicit permanent Keycloak support commitment. LDAP supports Active Directory. Reduces friction on every future deal, not one client.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (39,1,'Resolved a three-way TDF spec interpretation conflict (double encoding across internal and third-party SDK implementations), driving a spec update and coordinated SDK fixes.','sdk, opensource, architecture, judgment',NULL,'2025','TDF is an encrypted permanent format: no bulk re-encryption possible without massive audit signal. Ambiguous spec led two internal devs plus third-party companies to three different encodings. Spec was outside his domain but pushed the update through; SDKs were his domain.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (40,1,'Built compatibility matrix CI for cross-version, cross-language SDK validation; still core team infrastructure today.','sdk, reliability, process, devex','~10 recurring compat issues to 0','2025','Fixing the spec caused regressions parsing old TDFs, exposing a compatibility matrix problem. Go is the reference implementation but customers live in Java/JavaScript, causing drift and support confusion about which SDK version supported what.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (41,1,'Initiated WASM research to reduce SDK maintenance burden and extend language support (Python, Rust), targeting JavaScript first based on latency analysis.','sdk, devex, architecture, judgment',NULL,'2025','Key architectural instinct: distinguish human-perceived latency (JS clients, WASM acceptable) from machine-to-machine paths (latency-critical). Deliberate tradeoff, not blanket application.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (42,1,'Drove a support-escalation turnaround: platform issue calls requiring executive intervention and hour-plus biweekly meetings reduced to 15-30 minute check-ins tracking 1-2 items.','reliability, leadership, process','hour+ exec-driven calls to 15-30 min','2025','Issues got bad enough an executive came in to drive resolution. Fully engaged tracking platform issues across FDE/federal CSM/support/ops calls, prioritizing critical fixes, deferring low-priority, solving some via documentation instead of code to protect team bandwidth for federation, HSM, FIPS, post-quantum work.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (43,1,'Expanded team strategically: created a new Developer Experience role, added web administration headcount, and grew the platform team by two engineers.','people, leadership, devex','+2 platform engineers','2025','Note for role targeting: energized by technical sequencing and matching people to problems, NOT org-building/budget administration. Signals Principal/Architect over people-management VP. Does not want to apply to VP roles.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (44,1,'Drove strategic case for SaaS dogfooding of the Data Security Platform with the SVP of Engineering, securing a dedicated business unit to build a real product on it.','strategy, saas, leadership, platform',NULL,'2025','Core insight: company sold the platform with guarantees but only used it in QA. Real customer signal was filtered through FDEs, especially weak for federal customers. Business unit mandate was to BUILD a product on the platform, not just deploy it, so real usage feeds back into core.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (45,1,'Personally built the initial SaaS platform scaffold using OpenTDF extension patterns, establishing anti-drift architecture so SaaS features remain portable back to on-prem.','saas, architecture, platform, judgment',NULL,'2025','Guarded against internal-team mindset of freely modifying in-house libraries. DSP is an on-prem customer product; unchecked SaaS drift means two divergent codebases and teams forever. Leadership wanted both offerings long-term, so portability was mandatory. Built it himself so the pattern was set correctly day one, plus structural guardrails.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (46,1,'Staffed the new SaaS business unit for success: placed a technical lead and momentum engineer plus an engineering manager to seed platform expertise.','people, saas, leadership',NULL,'2025','Unit was not under his org but he ensured it did not start from zero platform knowledge. Facilitated end-of-year reshuffling.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (47,1,'Delivered full key-management modality matrix: Vault-style managed keys, AWS KMS, GCP KMS, and HSM (root key custody and rewrap), coordinating crypto and policy-administration teams.','crypto, architecture, leadership, platform','4 backends shipped + HSM enhancements','2026-01','Defined the taxonomy himself before teams could build to a shared model: default (DSP stores private keys wrapped by root key, Vault-like, not production-advised), KMS holding private key, KMS holding root key, HSM holding root key and optionally performing rewrap. Complex in both crypto engineering and policy-admin infrastructure. All shipped.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (48,1,'Guided the Claude Library launch, the platform''s first ABAC-based data sharing product, born from the SaaS dogfooding initiative.','saas, product-collab, architecture, leadership','first ABAC product on platform','2026-02','Grassroots product from dogfooding. Shift from email-based ACLs to attribute-based access control. Coordinated and guided the team, ensured platform alignment, while protecting his own team''s on-prem commitments.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (49,1,'Architected and delivered config service: a contract-first (protobuf + buf validate) centralized control plane unifying configuration across all platform PEPs.','platform, architecture, reliability, product-collab',NULL,'2026-02','Architected 2025, delivered Feb 2026 after deprioritization; handed to web admin team to roll out per-PEP. Problem: on-prem enterprise customers with 2-3 person teams cannot run 15 disparate services or assume Kubernetes. PEPs must enforce policy consistently or org-wide data privacy fails (zero-trust assumption). Contract-first design guards against version skew: old PEPs must work against newer platforms since customer upgrade timing is uncontrollable.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (50,1,'Held a team-derived 6-month delivery estimate for SaaS DSP early adopters against repeated executive pressure to pull the date in, converting potential serial misses into a single controlled two-week slip.','leadership, judgment, saas, process','end-June target, landed early July','2026-03','Collaborate went from dogfood project to committed product launch in March, changing pace and stakes. Descoped the most team-impactful items though leadership held the timeline. Pressure to move the date earlier recurred through April; held firm. Estimation done WITH the team, not unilaterally. Strong STAR story for protecting teams.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (51,1,'Scoped honest SaaS boundaries with Product and Marketing after isolated multi-tenancy (Kubernetes virtual clusters) was rejected: SaaS as a scoped offering, full control requiring self-hosting.','saas, strategy, judgment, product-collab',NULL,'2026-03','Pushed for per-customer isolated platform instances via K8s vclusters with full federation control; org pushed back. Rather than overpromise, drew the line: SaaS gets a reduced platform, customers wanting full key management and control self-host. Protected platform integrity. Deployed the makeshift multi-tenant version for the Collaborate team and helped them architect around platform design patterns.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (52,1,'Devised scoped-namespace, single-database deployment strategy to reach a fast SaaS platform win despite SRE capacity constraints.','saas, architecture, judgment',NULL,'2026-Q2','Pragmatic descoping under infrastructure support constraints. Rough capture, expand later.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (53,1,'Built an MCP solution on top of the platform CLI, enabling AI agents to operate the data security platform.','devex, platform, architecture',NULL,'2026-Q2','Flagged for deep dive and potential blog post: APIs vs SDKs vs CLIs as agent interfaces, and how agents actually consume MCPs and CLIs differently from traditional integration patterns. Timely topic for job market.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (54,1,'Developed tagging PDP with client-side content extraction and client-side tagging capabilities.','platform, architecture, security',NULL,'2026-Q2','Rough capture, deep dive planned. Policy Decision Point for tagging; extraction and tagging happen client-side.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (55,1,'Authored the organization''s AI development policy and blocked unreviewed AI-generated experimental code from reaching production.','ai-governance, leadership, judgment, process',NULL,'2026-Q2','Executives and product were AI-coding experimental solutions and pushing them toward prod. Took a stand: cannot support as-is, need a right way. Core concern: unreviewed AI-generated code and tests, people assuming correctness rather than verifying. Highly relevant story for current market: responsible AI adoption in engineering orgs.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (56,1,'Designed fine-grained access control solution that also resolved emergent multi-tenancy issues.','security, architecture, saas, platform',NULL,'2026-Q1','Built in Q1, mentioned during Q2 recap. Ryan flagged pride in this one. Deep dive planned.');
INSERT INTO accomplishments ("id","role_id","bullet","tags","metric","date_added","notes") VALUES (57,1,'Defended team-critical headcount when a role was unilaterally cancelled above him, successfully making the case for actual team needs.','leadership, people, judgment',NULL,'2026-Q2','SVP of Engineering went around him, cancelled an approved role and substituted a different DX role. Stood up and articulated what the team actually needed. Context: part of broader trust breakdown with SVP. Handle framing carefully in interviews: advocacy story, not grievance story.');

-- targets: 2 rows
INSERT INTO targets ("name","headline","summary","include_tags","boost_tags","exclude_tags","max_bullets_per_role","num_highlights") VALUES ('staff-architect','Platform Architect | Privacy-First Product Builder','Platform-focused engineering leader and architect with a proven track record of driving product innovation, developer experience, and system reliability at scale. Architect of high-impact Go-based platforms, with deep experience in cloud-native technologies and privacy-preserving systems. Known for delivering results months ahead of title changes, often operating in staff and director capacities across product, engineering, and strategy.','architecture, platform, go, devex, reliability, migration, api, kubernetes, cli, monorepo, microfrontends, typescript, scale, identity, crypto, security, sdk, saas, judgment, product-collab, ai-governance, opensource','architecture, platform, identity, security, judgment',NULL,5,5);
INSERT INTO targets ("name","headline","summary","include_tags","boost_tags","exclude_tags","max_bullets_per_role","num_highlights") VALUES ('principal-security','Principal Engineer | Data-Centric Security & Identity','Principal-level platform architect specializing in data-centric security: identity federation (OIDC, DPoP, token exchange), enterprise key management (HSM, KMS, KAS), and policy-driven access control (ABAC) on open-source foundations (OpenTDF). Combines deep hands-on technical execution with the judgment to know what not to build — protecting platform coherence, drawing honest product boundaries, and establishing responsible AI development practices.','identity, crypto, security, architecture, platform, sdk, opensource, judgment, ai-governance, saas, devex, go, api, cli','identity, crypto, security, judgment','frontend, microfrontends, revenue',6,5);
